# Generated by Django 4.1.2 on 2022-11-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_transfer',
            options={'ordering': ['user_transfer'], 'verbose_name': 'Показания', 'verbose_name_plural': 'Показания'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['user_service'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='data_transfer',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
